### ISSUE TITLE
node v12.18.3-1 exits with "Illegal Instruction"

### ISSUE THREAD

**Issue by foodtourama** [Entware/Entware#544] opened 2020-09-28 23:25 UTC
Hi!
Installed node v12.18.3-1 and node-npm
I'm on latest Entware for an ASUS router FW 384.6:
Linux RT-AC56U-A5C0 2.6.36.4brcmarm #1 SMP PREEMPT Wed Jul 25 12:43:03 EDT 2018 armv7l ASUSWRT-Merlin

My ASUS router has 256 MB RAM, 2 core 800 MHz armv7l (32 bit)
Every time I try to run node or npm, they exit with "Illegal Instruction"

What can be the problem?
The only command that works is "node -v" and it displays the version correctly... Anything else exits with "Illegal instruction", also npm command.

Cheers!

**Comment by zyxmon** [comment] 2020-09-29 05:34
Duplicate of https://github.com/Entware/Entware/issues/233

**Closed as completed by zyxmon** 2020-09-29 05:34 UTC
