### ISSUE TITLE
Borg backup is incompatible with the 1.0.7+ versions of python3-msgpack

### ISSUE THREAD

**Issue by DanielLester83** [Entware/Entware#1036] opened 2024-04-08 07:07 UTC
[The mentioned work around below now breaks because the version is too low. It is unnecessary to implement now] 

**Describe the bug**
[package name]: Starting the current version of borg backup server (borg serve) gives an error on attempted launch. Seems to work with 1.0.8, IF you edit /opt/lib/python3.11/site-packages/msgpack/__init__.py so the version lines say 1.0.2.

**Environment (please complete the following information):**
 - Device [e.g. Asus RT-AX88U router]
 - Firmware version [e.g. asuswrt-merlin]

**Comment by NRGDEAD** [comment] 2024-07-21 06:19
Duplicate of [this](https://github.com/Entware/Entware/issues/1033#issue-2198802501).

**Closed as completed** 2024-07-24 06:20 UTC
Labels: duplicate
