### ISSUE TITLE
New  libopenssl - 1.1.1t as well Stubby and GetDNS, Could we have those updated..Please !

### ISSUE THREAD

**Issue by Alozaros** [Entware/Entware#909] opened 2023-02-26 08:32 UTC
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.
Hi Entware team,
Could we have the new updated libopenssl - 1.1.1t... , along with getDNS and Stubby binaries as those are vital...for DNS security...

https://github.com/openssl/openssl

I'm  using those on multi platforms: ARM and Mips based routers..Thanks in advance !

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my platform Arm and Mips and get a feedback about it.

**Comment by ryzhovau** [comment] 2023-05-23 09:55
Duplicate of https://github.com/Entware/Entware/issues/839

**Closed as completed by ryzhovau** 2023-05-23 09:55 UTC
Labels: duplicate
