### ISSUE TITLE
rsync build without iconv support

### ISSUE THREAD

**Issue by pieter-v** [Entware/Entware#584] opened 2021-01-07 14:10 UTC
**Describe the bug**
rsync: previous versions of rsync (3.1.3-2) was build with iconv support. I need this option to sync files between mac and nas 
```
rsync --iconv="utf-8-mac,utf-8"
```
The support was probably removed in https://github.com/Entware/entware-packages/commit/9792fe8fe346ba3ae2e1b4151ddaaca4924466f4
```
	--disable-iconv \
	--disable-iconv-open \
```
**Environment:**
 - Entware feed: armv7sf-k3.2
 - Device ZyXEL NAS540

**Comment by ryzhovau** [comment] 2021-01-07 15:57
Fixed in upstream just few days ago, binaries will be updated on this week.

Closing as duplicate of https://github.com/Entware/Entware/issues/564

**Closed as completed by ryzhovau** 2021-01-07 15:57 UTC
Labels: duplicate
