### ISSUE TITLE
[Package request] orjson for homeassistant

### ISSUE THREAD

**Issue by WaveBird** [Entware/Entware#927] opened 2023-04-05 11:24 UTC
Hi, there, I am installing homeassistant and run into orjson compile which require rust and it failed, I really hope entware can make a pre-compiled pkg, thank you.

**Comment by ryzhovau** [comment] 2023-05-23 10:10
Duplicate of https://github.com/Entware/Entware/issues/863

**Closed as completed by ryzhovau** 2023-05-23 10:10 UTC
Labels: duplicate, new package

**Comment by ryzhovau** [comment] 2024-02-22 13:28
Rust packages has been added, including `python3-orjson`. Binaries will arrive soon
