### ISSUE TITLE
Please add ranger package

### ISSUE THREAD

**Issue by thienphuoc86** [Entware/Entware#691] opened 2021-09-24 14:15 UTC
**Describe the solution you'd like**
A clear and concise description of new features. Provide project URL and any other helpful context.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [ ] Package is in active development (at least, not abandoned for 5 years or more),
- [ ] I'm ready to test added package on my platform [e.g. mipselsf-k3.4] and get a feedback about it.

**Comment by thienphuoc86** [comment] 2021-09-24 14:15
Please add ranger package

**Comment by ryzhovau** [comment] 2021-09-25 13:09
Duplicate of #554

**Closed as completed by ryzhovau** 2021-09-25 13:09 UTC
Labels: duplicate
