### ISSUE TITLE
!!! Please update libtorrent-2.0.6 !!!

### ISSUE THREAD

**Issue by fireqpeg** [Entware/Entware#795] opened 2022-05-03 17:00 UTC
http://bin.entware.net/armv7sf-k3.2

device: RT-AX56U Firmware Version:[386.5_2]

https://www.libtorrent.org/upgrade_to_2.0-ref.html

Hello. Half a year has passed slowly. You haven't updated this program since. When libtorrent version 2.0.X.X came out. And I'd just be interested. When will libtorrent-rasterbar_2.0.6 be updated? The problem with the current version is libtorrent-rasterbar 1.2.15 doing high CPU utilization. And it crashes, it doesn't work properly, pretty much the problem with it. It has been interesting under openwrt for a very long time. I really hope. You will succeed as soon as possible. To solve this. Thanks in advance. Regards

**Comment by ryzhovau** [comment] 2022-05-03 17:58
Duplicate of https://github.com/Entware/Entware/issues/789

**Closed as completed by ryzhovau** 2022-05-03 17:58 UTC
Labels: duplicate
