### ISSUE TITLE
MTProto-proxy

### ISSUE THREAD

**Issue by brain5lug** [Entware/Entware#93] opened 2018-07-04 19:45 UTC
Package request
---
Official telegram messenger proxy
https://github.com/TelegramMessenger/MTProxy
---
Please, fill `{}` fields when asking for new package or delete this template in any other case.

**Comment by themiron** [comment] 2018-07-04 20:00
it supports x86 & x86-64 archs only

**Comment by Kirya2k** [comment] 2018-07-05 07:08
There is an unofficial implementation MTProxy based on the python3-cryptography library. Cryptography is present in Entware.
https://github.com/alexbers/mtprotoproxy
On which platform do you want to run MTProxy ?

**Comment by ryzhovau** [comment] 2018-07-06 18:32
Duplicate of #76 and #85.

**Closed as completed by ryzhovau** 2018-07-06 18:32 UTC
