### ISSUE TITLE
Package request: openfortivpn

### ISSUE THREAD

**Issue by romualdoag** [Entware/Entware#499] opened 2020-06-30 17:18 UTC
Package request: openfortivpn
---
openfortivpn is a client for PPP+SSL VPN tunnel services. It spawns a pppd process and operates the communication between the gateway and this process.

- [x] No similar package already added and/or this one got some new killer feature(s),
- [x] Package is in active development (at least, not abandoned for 5 years or more),
- [x] I'm ready to test added package on my mips and get a feedback about it.

---
https://github.com/adrienverge/openfortivpn

**Comment by ryzhovau** [comment] 2020-08-30 11:24
Duplicate of https://github.com/Entware/Entware/issues/327

**Closed as completed by ryzhovau** 2020-08-30 11:24 UTC
Labels: duplicate

**Comment by ryzhovau** [comment] 2021-02-13 17:42
We've received 3rd request and gave up. `openfortivpn` added recently.
